{
 "title": "File-server Application Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Node", "query": { "query": "label_values(host)" } },
   { "name": "Namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "File Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_memory_usage_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"file-server.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Nano Cores",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_cpu_usage_nanocores{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"file-server.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_tx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"file-server.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    },
    {
     "expr": "- rate(kubernetes_pod_network_rx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"file-server.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    }
   ]
  },
  { "title": "File Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Pod Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_memory_usage_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"file-client.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Nano Cores",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_cpu_usage_nanocores{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"file-client.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_tx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"file-client.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    },
    {
     "expr": "- rate(kubernetes_pod_network_rx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"file-client.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    }
   ]
  }
 ]
}