{
 "title": "Kubernetes Resources Usage",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Node", "query": { "query": "label_values(host)" } },
   { "name": "Namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_memory_usage_bytes{job=\"telegraf\",host=~\"^$Node$\", namespace=~\"kube-system\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_cpu_usage_nanocores{job=\"telegraf\",host=~\"^$Node$\", namespace=~\"kube-system\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_tx_bytes{job=\"telegraf\",host=~\"^$Node$\", namespace=~\"^$Namespace$\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    },
    {
     "expr": "- rate(kubernetes_pod_network_rx_bytes{job=\"telegraf\",host=~\"^$Node$\", namespace=~\"^$Namespace$\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    }
   ]
  }
 ]
}