{
 "title": "Observability Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Node", "query": { "query": "label_values(host)" } },
   { "name": "Namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Edge Data Center - Node Power & Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Node CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temp_temp{host=~\"^$Node$\", job=\"telegraf\"}",
     "legendFormat": "{{host}} - {{sensor}}"
    },
    {}
   ]
  },
  {
   "title": "Node Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "powerstat_package_current_power_consumption_watts{host=~\"^$Node$\", job=\"telegraf\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cluster - Node-level Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "cpu_usage_idle{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - idle",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - user"
    },
    {
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - system"
    },
    {
     "expr": "cpu_usage_iowait{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - iowait"
    },
    {
     "expr": "cpu_usage_steal{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - steal"
    },
    {
     "expr": "cpu_usage_guest{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - guest"
    },
    {
     "expr": "cpu_usage_guest_nice{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - guest_nice"
    },
    {
     "expr": "cpu_usage_irq{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - irq"
    },
    {
     "expr": "cpu_usage_softirq{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - softirq"
    }
   ]
  },
  {
   "title": "Systeml Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "system_load1{host=~\"^$Node$\",job=\"telegraf\"}",
     "legendFormat": "{{host}} - load1"
    },
    {
     "expr": "system_load5{host=~\"^$Node$\",job=\"telegraf\"}",
     "legendFormat": "{{host}} - load5"
    },
    {
     "expr": "system_load15{host=~\"^$Node$\",job=\"telegraf\"}",
     "legendFormat": "{{host}} - load15"
    }
   ]
  },
  {
   "title": "CPU Usage (System)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu0\"}",
     "legendFormat": "{{host}} - {{cpu}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu1\"}",
     "legendFormat": "{{host}} - {{cpu}} "
    },
    {
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu2\"}",
     "legendFormat": "{{host}} - {{cpu}} "
    },
    {
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu3\"}",
     "legendFormat": "{{host}} - {{cpu}}"
    },
    {
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu4\"}",
     "legendFormat": "{{host}} - {{cpu}} "
    },
    {
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu5\"}",
     "legendFormat": "{{host}} - {{cpu}}"
    },
    {
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu6\"}",
     "legendFormat": "{{host}} - {{cpu}}"
    },
    {
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu7\"}",
     "legendFormat": "{{host}} - {{cpu}} "
    }
   ]
  },
  {
   "title": "CPU Usage (User)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu0\"}",
     "legendFormat": "{{host}} - {{cpu}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu1\"}",
     "legendFormat": "{{host}} - {{cpu}} "
    },
    {
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu2\"}",
     "legendFormat": "{{host}} - {{cpu}}"
    },
    {
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu3\"}",
     "legendFormat": "{{host}} - {{cpu}} "
    },
    {
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu4\"}",
     "legendFormat": "{{host}} - {{cpu}}"
    },
    {
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu5\"}",
     "legendFormat": "{{host}} - {{cpu}} "
    },
    {
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu6\"}",
     "legendFormat": "{{host}} - {{cpu}}"
    },
    {
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu7\"}",
     "legendFormat": "{{host}} - {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Used (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "mem_used_percent{host=~\"^$Node$\", job=\"telegraf\"}",
     "legendFormat": "{{host}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Used (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "disk_used_percent{host=~\"^$Node$\", job=\"telegraf\", device=~\"sda2|nvme0n1p2\"}",
     "legendFormat": "{{host}} - {{device}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DiskIO (Reads/Writes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(diskio_reads{host=~\"^$Node$\", job=\"telegraf\"}[$__interval])",
     "legendFormat": "{{host}} - reads"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "- rate(diskio_writes{host=~\"^$Node$\", job=\"telegraf\"}[$__interval])",
     "legendFormat": "{{host}} - writes",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DiskIO (io_time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(diskio_io_time{host=~\"^$Node$\", job=\"telegraf\"}[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "DiskIO (read/write time)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(diskio_write_time{host=~\"^$Node$\", job=\"telegraf\"}[$__interval])",
     "legendFormat": "{{host}} - reads"
    },
    {
     "expr": "- rate(diskio_read_time{host=~\"^$Node$\", job=\"telegraf\"}[$__interval])",
     "legendFormat": "{{host}} -writes"
    }
   ]
  },
  {
   "title": "Network Packets (sent/recv)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(net_bytes_recv{host=~\"^$Node$\", job=\"telegraf\"}[$__rate_interval]))",
     "legendFormat": "{{host}} - recv",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "- sum(rate(net_bytes_sent{host=~\"^$Node$\", job=\"telegraf\"}[$__rate_interval]))",
     "legendFormat": "{{host}} - sent"
    }
   ]
  },
  {
   "title": "Cluster  - Overall Pod-level Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pods Running",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(kubernetes_pod_container_memory_usage_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\"}) by (host, pod_name))"
      }
     ]
    },
    {
     "title": "Pods Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum (kubernetes_pod_container_memory_usage_bytes{job=\"telegraf\",host=~\"^$Node$\", namespace=~\"^$Namespace$\"}) by (host)",
       "legendFormat": "{{host}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Pods CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum (rate (kubernetes_pod_container_cpu_usage_nanocores{host=~\"^$Node$\", namespace=~\"^$Namespace$\"}[1m]))",
       "legendFormat": "{{host}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Pods Network Usage",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate (kubernetes_pod_network_rx_bytes{job=\"telegraf\",host=~\"^$Node$\", namespace=~\"^$Namespace$\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Observability Agent - Usage Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }
  },
  {
   "title": "Telegraf - Pod Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "kubernetes_pod_container_memory_usage_bytes{host=~\"^$Node$\", namespace=~\"measurement\",  container_name=~\"tele.*\"}",
     "legendFormat": "{{host}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Nano Cores",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_cpu_usage_nanocores{host=~\"^$Node$\", namespace=~\"measurement\",  container_name=~\"tele.*\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Pod Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_tx_bytes{host=~\"^$Node$\", namespace=~\"measurement\", pod_name=~\"tele.*\"}[$__rate_interval])",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "- rate(kubernetes_pod_network_rx_bytes{host=~\"^$Node$\", namespace=~\"measurement\", pod_name=~\"tele.*\"}[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Promtail - Pod Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "kubernetes_pod_container_memory_usage_bytes{host=~\"^$Node$\", namespace=~\"measurement\",  container_name=~\"promtail.*\"}",
     "legendFormat": "{{host}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Nano Cores",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_cpu_usage_nanocores{host=~\"^$Node$\", namespace=~\"measurement\",  container_name=~\"promtail.*\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Pod Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_rx_bytes{host=~\"^$Node$\", namespace=~\"measurement\", pod_name=~\"promtail.*\"}[$__rate_interval])",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "- rate(kubernetes_pod_network_tx_bytes{host=~\"^$Node$\", namespace=~\"measurement\", pod_name=~\"promtail.*\"}[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Jaeger - Pod Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "kubernetes_pod_container_memory_usage_bytes{host=~\"^$Node$\", namespace=~\"observability\",  pod_name=~\"jaeger-agent.*\"}",
     "legendFormat": "{{host}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Nano Cores",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_cpu_usage_nanocores{host=~\"^$Node$\", namespace=~\"observability\",  pod_name=~\"jaeger-agent.*\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Pod Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_tx_bytes{host=~\"^$Node$\", namespace=~\"observability\",  pod_name=~\"jaeger-agent.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} "
    },
    {
     "expr": "- rate(kubernetes_pod_network_rx_bytes{host=~\"^$Node$\", namespace=~\"observability\",  pod_name=~\"jaeger-agent.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} "
    }
   ]
  },
  {
   "title": "Observability Server - Usage Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true
  },
  {
   "title": "Observability - Pod Memory Usage (Bytes)",
   "type": "stat",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_memory_usage_bytes{job=\"telegraf\",host=~\"^$Node$\", namespace=~\"observability\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}