{
 "title": "IoT Application Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Node", "query": { "query": "label_values(host)" } },
   { "name": "Namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Flask Web Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_memory_usage_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"web-ui.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Nano Cores",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_cpu_usage_nanocores{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"web-ui.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_tx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"web-ui.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    },
    {
     "expr": "- rate(kubernetes_pod_network_rx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"web-ui.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    }
   ]
  },
  { "title": "MySQL Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Pod Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_memory_usage_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"mysql.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Nano Cores",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_cpu_usage_nanocores{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"mysql.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_tx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"mysql.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    },
    {
     "expr": "- rate(kubernetes_pod_network_rx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"mysql.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    }
   ]
  },
  { "title": "MQTT Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Pod Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_memory_usage_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"mqtt-mosquitto.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Nano Cores",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_cpu_usage_nanocores{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"mqtt-mosquitto.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_tx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"mqtt-mosquitto.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    },
    {
     "expr": "- rate(kubernetes_pod_network_rx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"mqtt-mosquitto.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    }
   ]
  },
  { "title": "Kafka Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_memory_usage_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"bitnami.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Nano Cores",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_cpu_usage_nanocores{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"bitnami.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_tx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"bitnami.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    },
    {
     "expr": "- rate(kubernetes_pod_network_rx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  pod_name=~\"bitnami.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    }
   ]
  },
  { "title": "Sensors (Publishers) -> MQTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Pod Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_memory_usage_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  container_name=~\"pub.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Nano Cores",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_cpu_usage_nanocores{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  container_name=~\"pub.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_tx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\", pod_name=~\"pub.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    },
    {
     "expr": "- rate(kubernetes_pod_network_rx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\", pod_name=~\"pub.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    }
   ]
  },
  {
   "title": "Subscriber (MQTT -> Kafka)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true
  },
  {
   "title": "Pod Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_memory_usage_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  container_name=~\"mqtt-to-k.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Nano Cores",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_cpu_usage_nanocores{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  container_name=~\"mqtt-to-k.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_tx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\", pod_name=~\"mqtt-to-k.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    },
    {
     "expr": "- rate(kubernetes_pod_network_rx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\", pod_name=~\"mqtt-to-k.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    }
   ]
  },
  {
   "title": "Analyzer (Kafka -> MQTT, Kafka -> Datastore)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 }
  },
  {
   "title": "Pod Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_memory_usage_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  container_name=~\"temp-analyzer.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Nano Cores",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_cpu_usage_nanocores{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  container_name=~\"temp-analyzer.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_tx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\", pod_name=~\"temp-analyzer.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    },
    {
     "expr": "- rate(kubernetes_pod_network_rx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\", pod_name=~\"temp-analyzer.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    }
   ]
  },
  {
   "title": "Actuator <- MQTT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true
  },
  {
   "title": "Pod Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_memory_usage_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  container_name=~\"temp-actuator.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Nano Cores",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kubernetes_pod_container_cpu_usage_nanocores{host=~\"^$Node$\", namespace=~\"^$Namespace$\",  container_name=~\"temp-actuator.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_tx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\", pod_name=~\"temp-actuator.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    },
    {
     "expr": "- rate(kubernetes_pod_network_rx_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\", pod_name=~\"temp-actuator.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{pod_name}}"
    }
   ]
  }
 ]
}