---
- name: Add Promtail Helm repo
  when: install_promtail
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: "https://grafana.github.io/helm-charts"

- name: Install Promtail using Helm
  when: install_promtail
  kubernetes.core.helm:
    kubeconfig: "{{ kubernetes_config_path }}"
    name: promtail
    chart_ref: grafana/promtail
    release_namespace: measurement
    values_files:
      - "{{ playbook_dir }}/../helm-configs/promtail-values.yaml"

- name: Wait for Pods to start
  ansible.builtin.shell: sleep 60
  when: install_promtail

- name: Create Telegraf Service
  when: install_telegraf
  kubernetes.core.k8s:
    kubeconfig: "{{ kubernetes_config_path }}"
    state: present
    src: "{{ playbook_dir }}/../tools/telegraf/serviceaccount.yaml"

- name: Deploy Telegraf Agent on amd64 Worker Nodes
  when: install_telegraf
  kubernetes.core.k8s:
    kubeconfig: "{{ kubernetes_config_path }}"
    state: present
    src: "{{ playbook_dir }}/../tools/telegraf/amd64-workers.yaml"

- name: Deploy Telegraf Agent on arm64 Worker Nodes
  when: install_telegraf
  kubernetes.core.k8s:
    kubeconfig: "{{ kubernetes_config_path }}"
    state: present
    src: "{{ playbook_dir }}/../tools/telegraf/arm64-workers.yaml"

- name: Deploy Telegraf Agent on Master Node
  when: install_telegraf
  kubernetes.core.k8s:
    kubeconfig: "{{ kubernetes_config_path }}"
    state: present
    src: "{{ playbook_dir }}/../tools/telegraf/master.yaml"